### PR TITLE
Rework `EmberNameIndex` into `CachedValue`

### PR DESCRIPTION
**Pull request by Turbo87**
This PR is basically https://github.com/stukalin/intellij-emberjs/pull/3 rebased on top of the official `master` branch

Thanks a lot @tomblachut!! 🙏

### CODE REVIEW

**Comment by tomblachut** [comment]
You're welcome, I see that now tests pass even on previous platform :) Do not hesitate to ask if something is not clear enough. EmberNameIndex could also extend SingleEntryFileBasedIndexExtension to simplify implementation a bit.

**Comment by Turbo87** [comment]
I plan on running this version over the next couple of days and unless any issues pop up I'll merge and release this some time next week :)

**Comment by Turbo87** [comment]
and for anyone else who wants to try this out: `./gradlew buildPlugin` and then manually install the plugin from disk (`./build/distributions/...`)

**Comment by Turbo87** [comment]
I haven't noticed any issues with this so far, so once again: thank you @tomblachut :)

**Pull request merged**
