### PR TITLE
Update IntelliJ to v2020.3

### PR DESCRIPTION
**Pull request by Turbo87**
unfortunately our test are currently failing with:

```
com.emberjs.navigation.EmberGotoRelatedProviderTest > testCratesIo FAILED
    java.lang.AssertionError: ID with name 'ember.names' requested for plugin null but registered for com.emberjs
        at com.intellij.util.indexing.ID.findByName(ID.java:95)
        at com.intellij.util.indexing.ID.create(ID.java:68)
        at com.emberjs.index.EmberNameIndex.<clinit>(EmberNameIndex.kt:27)
        at com.emberjs.navigation.EmberGotoRelatedProviderTest.doTest(EmberGotoRelatedProviderTest.kt:124)
        at com.emberjs.navigation.EmberGotoRelatedProviderTest.testCratesIo(EmberGotoRelatedProviderTest.kt:15)

        Caused by:
        java.lang.Throwable
            at com.intellij.util.indexing.ID.<init>(ID.java:54)
            at com.intellij.util.indexing.ID.create(ID.java:69)
            at com.emberjs.index.EmberNameIndex.<clinit>(EmberNameIndex.kt:27)
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
            at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
            at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:684)
            at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.instantiateClass(ExtensionComponentAdapter.java:51)
            at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:133)
            at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:43)
            at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:69)
            at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:472)
            at com.intellij.openapi.extensions.impl.ExtensionPointImpl.access$200(ExtensionPointImpl.java:37)
            at com.intellij.openapi.extensions.impl.ExtensionPointImpl$1.next(ExtensionPointImpl.java:367)
            at com.intellij.util.indexing.FileBasedIndexDataInitialization.initAssociatedDataForExtensions(FileBasedIndexDataInitialization.java:56)
            at com.intellij.util.indexing.FileBasedIndexDataInitialization.prepare(FileBasedIndexDataInitialization.java:92)
            at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.call(IndexInfrastructure.java:122)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
            at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
            at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
            at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
            at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
            at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
            at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
            at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
            at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
            at java.base/java.lang.Thread.run(Thread.java:832)
```

### CODE REVIEW

**Comment by Turbo87** [comment]
It looks like the `getCallerPlugin()` function in `PluginUtilImpl.java` returns `null`, because `classLoader` is an `AppClassLoader`, instead of the expected `PluginClassLoader`. Unfortunately I'm running out of ideas on how to fix this though 😞 

@denofevil any clues?

**Comment by piotrtomiak** [comment]
@Turbo87 Not sure why it's happening, but I would go for finding the index name through extension point to avoid direct class loading: 
```
FileBasedIndexExtension.EXTENSION_POINT_NAME.extensionList()
.asSequence()
.find{it.name.name == "ember.names" }
.let{FileBasedIndex.getInstance().requestRebuild(it.name)}
```
Please note that I haven't compiled the code above, so it may have some issues ;)

**Comment by makepanic** [comment]
Does this test failure happen in the github actions? 

The error in https://github.com/Turbo87/intellij-emberjs/pull/355/checks?check_run_id=1542981935#step:6:28 seems to point to an old java version. 

If i try to run the tests with openjdk 14 it completes successfully.
If i use openjdk 8, I get the same error that is reported in the github action.

**Comment by Turbo87** [comment]
> Does this test failure happen in the github actions?

locally too, but admittedly it is quite possible that I'm still running Java 8 locally too.

do you know what Java version the current IntelliJ release is based on?

**Comment by makepanic** [comment]
> do you know what Java version the current IntelliJ release is based on?

I'm not sure. Searching in the official intellij-plugins repo it seems like they all moved to java 11 in september:

* https://github.com/JetBrains/intellij-plugins/commit/16db0fe33e8140491be968e167fee75ed23123ee#diff-16736801c595cc4347c8c6eae6a1a1a173c80fb705aaca607196c30cb650bec7R7
* https://github.com/JetBrains/intellij-plugins/search?q=javaVersion

**Comment by Turbo87** [comment]
nice! thanks for that pointer @makepanic!! 🎉

**Pull request merged**
