### PR TITLE
Update IntelliJ to v2022.1

### PR DESCRIPTION
**Pull request by ChrisCarini**
# Summary

Update IntelliJ to v2022.1

# Testing Done
- [x] `./gradlew assemble` -> ✅  **_Success_**
- [x] `./gradlew check` -> ✅  **_Success_**
- [x] `./gradlew buildPlugin` -> ✅  **_Success_**
- [x] `./gradlew runIde` -> ✅  **_Success_**
    - [x] Confirmed IDE in sandbox started with no exceptions from `Ember.js` plugin thrown

### CODE REVIEW

**Comment by ChrisCarini** [comment]
@Turbo87 - since this is my first time contributing to this repo, it appears I'll need your approval for the CI checks to run.

**Review by Turbo87 — APPROVED** [review]
❤️  thanks!

I'll fill the changelog again once I do the next release :)

**Comment by ChrisCarini** [comment]
> ❤️ thanks!

@Turbo87 - no problem!

> I'll fill the changelog again once I do the next release :)

Cool! When are you planning on doing the next release? IJ 2022.1 is trying to downgrade the plugin to the very first version of this released (`2016.2.4-0`) 😞 
Screen Shot 2022-04-19 at 17 06 16

**Comment by Turbo87** [comment]
ideally after https://github.com/Turbo87/intellij-emberjs/issues/417 is fixed, but I haven't had time yet to look into that

**Pull request merged**
