### PR TITLE
Resolve absolute imports for addons

### PR DESCRIPTION
**Pull request by dwickern**
This makes absolute imports (#35, #103) work for addons also.

Notably if you are looking at a file in /app that re-exports from an addon like this,
```js
// app/components/power-select.js
export { default } from 'ember-power-select/components/power-select';
```

Then Ctrl/Cmd-clicking on `power-select` will navigate to `addon/components/power-select.js`

### CODE REVIEW

**Comment by Turbo87** [comment]
where does it point to when you `import Foo from 'foo-bar';`?

**Comment by dwickern** [comment]
IntelliJ can't typically resolve those. Same with `import Ember from 'ember'`

**Comment by Turbo87** [comment]
@dwickern I think I had a branch where I got it working in some form, but it wasn't that pretty either...

**Comment by dwickern** [comment]
`foo-bar` could technically resolve to anything, right? Only broccoli would know.

IntelliJ already checks `node_modules` for the exact module name. For example I have this code
```js
import BeforeOptions from 'ember-power-select/components/power-select/before-options';
BeforeOptions.reopen({ ... });
```

`ember-power-select` links me to `node_modules/ember-power-select`. The rest of the path doesn't link anywhere, but it could be made to work

**Comment by dwickern** [comment]
Ember isn't distributed as source code so we still would need typescript definitions for `import Ember from 'ember'`

**Comment by Turbo87** [comment]
> Ember isn't distributed as source code so we still would need typescript definitions for import Ember from 'ember'

yeah, `ember` is special at the moment...

my point about the foobar example above was more that it should resolve to the `index.js` file if it exists, I'm fine with the way it currently resolves into the `node_modules` folder

**Comment by dwickern** [comment]
```js
import BeforeOptions from 'ember-power-select/components/power-select/before-options';
```
It can resolve the above path to `node_modules/ember-power-select/{app,addon}`. It assumes that the addon name is equal to the npm package name which is generally true in practice https://github.com/lytics/ember-data-model-fragments/issues/245

It still does NOT support these imports.
```js
import Ember from 'ember';
import { expect } from 'chai';
import { describeComponent, it } from 'ember-mocha';
import Mirage, {faker} from 'ember-cli-mirage';
import Component from 'ember-component';
import { scheduleOnce } from 'ember-runloop';
import wait from 'ember-test-helpers/wait';
```
It looks like some of them use a different addon structure convention. e.g. emer-mocha and ember-test-helpers have their sources in `/lib` and have "main" set in package.json

**Comment by Turbo87** [comment]
bildschirmfoto 2017-05-07 um 09 14 38

@dwickern this doesn't seem to work for me yet 🤔

**Comment by dwickern** [comment]
Works for me. What project and source file did you test with?

**Comment by Turbo87** [comment]
good question. if I remember correctly it was a work project that is not OSS unfortunately... 🤔

**Comment by DuckoDeath** [comment]
This doesn't work for me (although very possible I am misunderstanding).
I am using the latest 2017.3.1-0 with Webstorm 2017.3 EAP.

I have 2 projects ('mainproj' plus an addon project 'sub').
mainproj/app/...
sub/addon/...
sub/app/...

from within mainproj/app/components/something.js
I have an import like:
`import Stuff from 'sub/mixins/stuff';`

Trying to navigate to stuff, still results in 'Cannot find declaration to go to'.
What am I missing?  Is this a different issue?

Thanks.

**Comment by dwickern** [comment]
@DuckoDeath What's the relationship between those projects? Is `sub` an in-repo addon?

**Comment by DuckoDeath** [comment]
No.  They are both parallel projects in the same dir (ie /work/proj, and /.work/sub).  Sub is then npm linked to mainproj.

**Comment by dwickern** [comment]
@DuckoDeath Are you running EAP version 2017.3? The release version of IDEA is 2017.2 which does not have this PR's changes yet.

**Comment by DuckoDeath** [comment]
I am using the latest 2017.3.1-0 with Webstorm 2017.3 EAP (WS-173.2941.6).

**Pull request merged**
