### PR TITLE
Update IntelliJ to v2021.2

### LINKED ISSUE #382: Navigation through components have broken in new WebStorm version
### Description

I've updated my WebStorm version to WebStorm 2021.2 and now the navigation through components is not working

### Steps to Reproduce

- I'm in a template
- I press "ctrl" and click on a Component tag

**Expected behavior:** [What you expect to happen]
- We should navigate to the component template

**Actual behavior:** [What actually happens]
- Nothing happens. WebStorm is not detecting the Component tag as a navigable link.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
WebStorm 2021.2
Build #WS-212.4746.80, built on July 23, 2021

- The version of `intellij-emberjs` (`Settings` -> `Plugins` -> `Ember.js`):
2016.2.4-0

### Additional Information

Looks like there is a bug in the Plugin version, or the new WebStorm version have changed the Plugin version to a very old one.

### PR DESCRIPTION
**Pull request by stukalin**
Fixes #382

### CODE REVIEW

**Comment by Turbo87** [comment]
looks like a few of the tests are failing 😢

**Comment by stukalin** [comment]
Ok, will fix tomorrow!

чт, 19 авг. 2021 г., 20:36 Tobias Bieniek ***@***.***>:

**Comment by stukalin** [comment]
@Turbo87 well, there is some issue apparently when it comes to the latest platform version. I asked the JB guys.

**Comment by Turbo87** [comment]
> I asked the JB guys.

did you hear anything? :)

**Comment by stukalin** [comment]
@Turbo87 well there was one comment on the issue (you might have a look) and the guy assigned the issue on himself, but tbh I haven't understood much from what he wrote(((

**Comment by tomblachut** [comment]
Hello I'm Tomasz from WebStorm 👋 I'm here to help with the update. I'm writing in this issue because I believe it's better place than gradle plugin repo. Sorry for the delay, I needed to understand Ember a bit. 

First of all, EmberNameIndex doesn't use file content, but it uses file location. Therefore it shouldn't be an index at all. Index subsystem is optimised to extract key information from files so they don't need to be opened from disk for every IDE operation. More importantly it works on files in isolation, not in specific place in file system. Indices team could have added some assertions to catch more edge cases inside tests, or maybe changed internal details, and Ember plugin broke, because it relied on internal bits.

I have some idea how to rework EmberNameIndex and will add another reply here, maybe even PR if you want.

**Comment by Turbo87** [comment]
> I have some idea how to rework EmberNameIndex and will add another reply here, maybe even PR if you want.

that would be wonderful, thanks :)

let me know if you have any questions on how things are intended to work

**Comment by tomblachut** [comment]
Thanks. I'm tinkering with https://github.com/gothinkster/ember-realworld, is it alright? Do you have some better example project around by any chance?

**Comment by Turbo87** [comment]
https://github.com/rust-lang/crates.io is a fairly up-to-date codebase that uses Ember.js for the frontend

**Comment by tomblachut** [comment]
OK I'm not that fluent in multiple-fork situations so it opened the PR in @stukalin fork, anyway it's linked above and I hope we can proceed with it, otherwise I can rebase my PR, let me know. I'll add some comments to the PR.

**Pull request merged**
