### PR TITLE
WIP: Import CLI code from official Angular plugin

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by dwickern** [comment]
This is great! I like having consistency between the CLI and IDE.

I have some small changes to make the generator work on my project.

**Comment by Turbo87** [comment]
@dwickern I have to admit that I'm not a huge fan of their UI design around this feature. I'm thinking about reusing our old dialog but using their method of parsing `ember help`.

**Comment by dwickern** [comment]
Yeah, I would prefer something closer to the standard "new file" dialog while still offering ember-cli blueprints.

I wonder if we could call ember-cli APIs to list the blueprints instead of parsing CLI output.

**Comment by Turbo87** [comment]
> I wonder if we could call ember-cli APIs to list the blueprints instead of parsing CLI output.

it would technically be possible, but we'd be using private APIs and I don't think that's a great idea. I have to admit that parsing the `ember help` output isn't such a great option either...

**Pull request closed without merging**
