### PR TITLE
Update IntelliJ platform to 2022.2

### PR DESCRIPTION
**Pull request by dwickern**

### CODE REVIEW

**Comment by Alonski** [comment]
Not releasing this means that anyone using latest Webstorm is reverted to using the Ember.js plugin from... 8 years ago in 2016!

**Comment by Turbo87** [comment]
@Alonski relax... I'm technically still on vacation. you can still use an older version of WebStorm for now or build the plugin zip file from this branch manually. I'll get this merged and release in the next couple of days.

**Comment by Alonski** [comment]
Sorry @Turbo87 !
I'll relax 😂
Didn't mean to disturb you on your vacation.
Safe flying!

**Comment by Alonski** [comment]
Thanks!

**Pull request merged**
