### PR TITLE
Add IntelliJ 14 compatibility

### LINKED ISSUE #6: Does not work with old IDE versions
Hey!

I wanted to try this plugin with my Webstorm 9 installation but I can not install it. During the installation I get the following error: 
```Error --> Plugin Ember.js is incompatible with current installation```
I have Webstorm 9.0.3 on Mac OS X Yosemite. Do I have a chance to get it running or is it really incompatible with my installation?

Thanks as lot

### PR DESCRIPTION
**Pull request by Turbo87**
This needs to be tested by a lot more people than just me before I feel confident merging this...!

This PR resolves #6

### CODE REVIEW

**Comment by jswhetstone** [comment]
Built from old-ide-compat branch.

Attempted to install on Intellij 14.1.6 (IU-141.3056)

Receeved error: 
> Plugin 'Ember.js' is incompatible with this installation

**Comment by Turbo87** [comment]
@jswhetstone thanks for the feedback. could you try setting `INTELLIJ_VERSION` to `14.1.2` in the `gradle.properties` file and then recompile the branch?

**Comment by jswhetstone** [comment]
Sorry, I should have specified; I did see that property in the
gradle.properties, and observed that changing it causes gradle to download
14.1.2 instead of 15, but the resulting plugin still won't install.

**Comment by Turbo87** [comment]
hmm, that's unfortunate. my guess is that we need to play around with the `<idea-version>` tag (see https://github.com/Turbo87/intellij-emberjs/blob/master/src/main/resources/META-INF/plugin.xml#L29) in the `plugin.xml` file and configure the IntelliJ Gradle plugin to not mess around with it. 

it might also be necessary to compile the plugin with Java 6 instead, which would have some other unfortunate consequences...

**Comment by jswhetstone** [comment]
Your current tag should work for 14.1 though.

I don't know if it makes a difference for compiling, but Idea is currently using JRE 1.8 in my install.

**Comment by Turbo87** [comment]
@jswhetstone I had to set `updateSinceUntilBuild = false` in the Gradle plugin, otherwise the `<idea-version>` tag was just overwritten. I've also had a few issues when using the plugin compiled for Java 1.8 and now I'm setting the `sourceCompatibility` property in the Gradle file to 1.7 which seem to have fixed the problem.

I'm running the IU-141.3056 release here too now, and I've managed to install the plugin via zip file into it. Please try to reproduce my success and if that works I think we might be ready to merge this.

**Pull request merged**
