### PR TITLE
Add application settings to exclude node and bower folders

### LINKED ISSUE #24: Optionally exclude node_modules and bower_components folder
As suggested in #22 we should add a plugin-wide option whether the `node_modules` and `bower_components` folder should be marked as library folders or instead excluded from indexing at all. I would personally use the first option because once the initial index is done it usually stays quite fast but I can see that people might disagree.

### PR DESCRIPTION
**Pull request by Turbo87**
This PR resolves #24.

/cc @panthony @dfreeman @runspired @Ramblurr @k3n please test if this works for you, then I'll officially release this. you may have to reimport the project or restart the IDE.

### CODE REVIEW

**Comment by Ramblurr** [comment]
Awesome! Thanks @Turbo87, I'll test this tomorrow.

**Comment by panthony** [comment]
Thanks @Turbo87 !

For node_modules I simply had to restart the IDE to be taken into account.

For bower_components I had to reimport the project like you said.

But in the end I think I'll just exclude node_modules because if you exclude bower_components you'll have a bunch of unresolved methods for Ember which is very annoying.

**Comment by Turbo87** [comment]
> But in the end I think I'll just exclude node_modules because if you exclude bower_components you'll have a bunch of unresolved methods for Ember which is very annoying.

I hope you're aware that in the near future Ember will move from Bower to NPM too :wink: 

Thanks for testing this out though. I'll prepare a new release in the next days including this PR unless anyone still reports issues with it.

**Comment by panthony** [comment]
They may move to NPM 'soon' but I have some times ahead of me before I can migrate my app to the latest release :)

I did not really have performances issues with node_modules being indexed. It was more the Navigate by class that returns a bunch of classes from third parties libraries on top of my own which where annoying.

**Comment by Ramblurr** [comment]
Used it all day today and it worked great.

**Comment by Ramblurr** [comment]
@panthony As a work around to to indexing all of node_modules, including the 2nd level dependencies you don't care about, you can exclude node_modules, then create a new library group in your module settings with just the dependencies you use. I selected all the deps that started with ember.

@Turbo87 Would it be possible to analyze, package.json and only mark those direct dependencies as libraries?

**Comment by Turbo87** [comment]
@Ramblurr it's certainly possible, but I personally won't spend any time on that for now.

**Comment by panthony** [comment]
@Ramblurr That's a pretty good idea, thanks :+1:

**Comment by Turbo87** [comment]
merging now

@Ramblurr thanks for your feedback!

**Pull request merged**
