### PR TITLE
[WIP] Add support for multiple modules

### LINKED ISSUE #53: Plugin doesn't seem to work with multiple modules
Hi! I am not sure if I am doing it right, in which case please correct me. I have a project which consists of a few ruby services and a couple of emberjs apps. So I decided to add those as module to an empty IntelliJ project. I go to Project Structure, Add > Import module. The module is correctly identified as EmberJS. But when added the app folder is not recognized as source root, neither are node_modules and bower_components and pretty much nothing works.  I want to note that if I open the folder as a separate project, rather than as module it will work just fine.

### PR DESCRIPTION
**Pull request by dwickern**
This PR makes the plugin operate on modules instead of projects.

You can import in more ways than before:
- import an ember app as a project using `File -> New -> Project From Existing Sources...` (this works as before because the root project is also a module)
- import an ember app into an existing project using `File -> New -> Module From Existing Sources...`
- import using another build system (sample projects included for Maven, SBT)

You can have more than one ember application in a project. The Generate Code action will now generate code for the selected module.

Closes #53

### CODE REVIEW

**Comment by dwickern** [comment]
This is based on an older commit for now. I couldn't get my environment working on master because of JetBrains/gradle-intellij-plugin#145

**Comment by Turbo87** [comment]
@dwickern did you see the last paragraph of https://github.com/JetBrains/gradle-intellij-plugin/issues/145#issuecomment-258672371?

**Comment by dwickern** [comment]
@Turbo87 that seems to work :+1: I'll rebase onto master

I noticed that the `app` and `tests` folders are not highlighted as source roots after importing as a module. Everything still works, and if I close and open the project they will be highlighted. I'm probably missing some sort of `refresh()` call somewhere...

**Comment by Turbo87** [comment]
@dwickern I've just pushed a `cli` branch to this repo that imports some of the Angular plugin code. This also includes a different way to generating blueprints which possibly conflicts with this PR. Could you have a look whether we could make it compatible?

I also have a feeling that having a dedicated `EmberModule` was a bad idea and that we should be using the `FrameworkDetector` class instead (like the Angular plugin does too).

**Comment by dwickern** [comment]
I can merge with your branch, no problem.

Hit me up in slack if you want to chat about the module vs framework thing.

**Pull request closed without merging**
