### PR TITLE
Add option to run `ember-template-lint --fix` on save

### PR DESCRIPTION
**Pull request by dwickern**
Screen Shot 2021-11-09 at 7 47 23 PM

Screen Shot 2021-11-09 at 7 47 41 PM

Also adds it as a regular action when right-clicking hbs files:

Screen Shot 2021-11-09 at 7 47 52 PM

### CODE REVIEW

**Review by Turbo87 — APPROVED** [review]
works great! nice job 👏

**Comment by Alonski** [comment]
Wanted to say that it seems that this doesn't work anymore.
@Turbo87 or @dwickern Any ideas why?

**Comment by dwickern** [comment]
@Alonski This plugin hasn't been released yet for IntelliJ 2022.2 (see #453). You're likely running an old plugin from 2016 which claims compatibility with any IntelliJ version.

**Comment by Alonski** [comment]
Hmm 🤔 how do I check that?

**Comment by dwickern** [comment]
Settings -> Plugins and then search for ember

**Comment by Alonski** [comment]
@dwickern Oof I see that now 🙃 
Nothing to do except wait for your fix to get merged?

**Pull request merged**
